<?php
// rule_key: quantum.arq-q-0683-php
// evidence_anchor: CURLOPT_SSLVERSION / STREAM_CRYPTO_METHOD_TLSv1_0
// regex_sample: TLS1.0
// keywords: CURLOPT_SSLVERSION | TLSv1 | STREAM_CRYPTO_METHOD_TLSv1_0 | STREAM_CRYPTO_METHOD_TLSv1_1
CURLOPT_SSLVERSION / STREAM_CRYPTO_METHOD_TLSv1_0
